### ISSUE TITLE
node server.js

### ISSUE THREAD

**Issue by chonnochara** [BlackYoup/NodeJS-COD4-MasterServer#2]
Nothing happens when I execute the command "node server.js" I have also installed "npm install colors" yet nothing happens when i enter that command. Could you please help me out?

**Comment by BlackYoup** [comment]
Hi,

I've updated the entry point which is `app.js`. Please note that this was mostly a test at the time and used to run on node `0.10` or `0.12`, didn't test above versions.

Thanks for the report though.
